# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanoidApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=200)),
                ('height_cm', models.FloatField(default=180)),
                ('weight_kg', models.FloatField(default=70)),
                ('chest_cm', models.FloatField(default=0)),
                ('waist_cm', models.FloatField(default=0)),
                ('age', models.FloatField(default=0)),
                ('body_fat_distribution', models.FloatField(default=0.5)),
            ],
        ),
    ]
