# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='humanoidapi',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='humanoidapi',
            name='gender',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='humanoidapi',
            name='key_string',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='humanoidapi',
            name='skin_color',
            field=models.CharField(default='1', max_length=6),
        ),
    ]
