# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_prod', '0002_auto_20171218_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='humanoidapi',
            name='image_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='humanoidapi',
            name='name',
            field=models.CharField(default='Username', max_length=200),
        ),
        migrations.AlterField(
            model_name='humanoidapi',
            name='skin_color',
            field=models.CharField(default='', max_length=6),
        ),
    ]
