# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humanoid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(default='nabeel', max_length=200)),
                ('gender', models.FloatField(default=1.0)),
                ('age', models.IntegerField(default=23)),
                ('weight', models.FloatField(default=0.5)),
                ('muscle', models.FloatField(default=0.5)),
                ('height', models.IntegerField(default=180)),
            ],
        ),
    ]
